# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dsampaio/Desenvolvimento/MelanciaSoftware/projects/loopadrome

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dsampaio/Desenvolvimento/MelanciaSoftware/projects/loopadrome

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dsampaio/Desenvolvimento/MelanciaSoftware/projects/loopadrome/CMakeFiles /home/dsampaio/Desenvolvimento/MelanciaSoftware/projects/loopadrome//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dsampaio/Desenvolvimento/MelanciaSoftware/projects/loopadrome/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/dsampaio/Desenvolvimento/MelanciaSoftware/projects/loopadrome/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named loopadrome_BINARY

# Build rule for target.
loopadrome_BINARY: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 loopadrome_BINARY
.PHONY : loopadrome_BINARY

# fast build rule for target.
loopadrome_BINARY/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/build
.PHONY : loopadrome_BINARY/fast

src/data/avl_tree.o: src/data/avl_tree.c.o
.PHONY : src/data/avl_tree.o

# target to build an object file
src/data/avl_tree.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/data/avl_tree.c.o
.PHONY : src/data/avl_tree.c.o

src/data/avl_tree.i: src/data/avl_tree.c.i
.PHONY : src/data/avl_tree.i

# target to preprocess a source file
src/data/avl_tree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/data/avl_tree.c.i
.PHONY : src/data/avl_tree.c.i

src/data/avl_tree.s: src/data/avl_tree.c.s
.PHONY : src/data/avl_tree.s

# target to generate assembly for a file
src/data/avl_tree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/data/avl_tree.c.s
.PHONY : src/data/avl_tree.c.s

src/data/list.o: src/data/list.c.o
.PHONY : src/data/list.o

# target to build an object file
src/data/list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/data/list.c.o
.PHONY : src/data/list.c.o

src/data/list.i: src/data/list.c.i
.PHONY : src/data/list.i

# target to preprocess a source file
src/data/list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/data/list.c.i
.PHONY : src/data/list.c.i

src/data/list.s: src/data/list.c.s
.PHONY : src/data/list.s

# target to generate assembly for a file
src/data/list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/data/list.c.s
.PHONY : src/data/list.c.s

src/ecs/component.o: src/ecs/component.c.o
.PHONY : src/ecs/component.o

# target to build an object file
src/ecs/component.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/ecs/component.c.o
.PHONY : src/ecs/component.c.o

src/ecs/component.i: src/ecs/component.c.i
.PHONY : src/ecs/component.i

# target to preprocess a source file
src/ecs/component.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/ecs/component.c.i
.PHONY : src/ecs/component.c.i

src/ecs/component.s: src/ecs/component.c.s
.PHONY : src/ecs/component.s

# target to generate assembly for a file
src/ecs/component.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/ecs/component.c.s
.PHONY : src/ecs/component.c.s

src/ecs/entity.o: src/ecs/entity.c.o
.PHONY : src/ecs/entity.o

# target to build an object file
src/ecs/entity.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/ecs/entity.c.o
.PHONY : src/ecs/entity.c.o

src/ecs/entity.i: src/ecs/entity.c.i
.PHONY : src/ecs/entity.i

# target to preprocess a source file
src/ecs/entity.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/ecs/entity.c.i
.PHONY : src/ecs/entity.c.i

src/ecs/entity.s: src/ecs/entity.c.s
.PHONY : src/ecs/entity.s

# target to generate assembly for a file
src/ecs/entity.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/ecs/entity.c.s
.PHONY : src/ecs/entity.c.s

src/ecs/system.o: src/ecs/system.c.o
.PHONY : src/ecs/system.o

# target to build an object file
src/ecs/system.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/ecs/system.c.o
.PHONY : src/ecs/system.c.o

src/ecs/system.i: src/ecs/system.c.i
.PHONY : src/ecs/system.i

# target to preprocess a source file
src/ecs/system.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/ecs/system.c.i
.PHONY : src/ecs/system.c.i

src/ecs/system.s: src/ecs/system.c.s
.PHONY : src/ecs/system.s

# target to generate assembly for a file
src/ecs/system.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/ecs/system.c.s
.PHONY : src/ecs/system.c.s

src/game/engine.o: src/game/engine.c.o
.PHONY : src/game/engine.o

# target to build an object file
src/game/engine.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/game/engine.c.o
.PHONY : src/game/engine.c.o

src/game/engine.i: src/game/engine.c.i
.PHONY : src/game/engine.i

# target to preprocess a source file
src/game/engine.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/game/engine.c.i
.PHONY : src/game/engine.c.i

src/game/engine.s: src/game/engine.c.s
.PHONY : src/game/engine.s

# target to generate assembly for a file
src/game/engine.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/game/engine.c.s
.PHONY : src/game/engine.c.s

src/game/window/win_entity.o: src/game/window/win_entity.c.o
.PHONY : src/game/window/win_entity.o

# target to build an object file
src/game/window/win_entity.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/game/window/win_entity.c.o
.PHONY : src/game/window/win_entity.c.o

src/game/window/win_entity.i: src/game/window/win_entity.c.i
.PHONY : src/game/window/win_entity.i

# target to preprocess a source file
src/game/window/win_entity.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/game/window/win_entity.c.i
.PHONY : src/game/window/win_entity.c.i

src/game/window/win_entity.s: src/game/window/win_entity.c.s
.PHONY : src/game/window/win_entity.s

# target to generate assembly for a file
src/game/window/win_entity.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/game/window/win_entity.c.s
.PHONY : src/game/window/win_entity.c.s

src/game/window/win_system.o: src/game/window/win_system.c.o
.PHONY : src/game/window/win_system.o

# target to build an object file
src/game/window/win_system.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/game/window/win_system.c.o
.PHONY : src/game/window/win_system.c.o

src/game/window/win_system.i: src/game/window/win_system.c.i
.PHONY : src/game/window/win_system.i

# target to preprocess a source file
src/game/window/win_system.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/game/window/win_system.c.i
.PHONY : src/game/window/win_system.c.i

src/game/window/win_system.s: src/game/window/win_system.c.s
.PHONY : src/game/window/win_system.s

# target to generate assembly for a file
src/game/window/win_system.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/game/window/win_system.c.s
.PHONY : src/game/window/win_system.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/main.c.s
.PHONY : src/main.c.s

src/opengl/error.o: src/opengl/error.c.o
.PHONY : src/opengl/error.o

# target to build an object file
src/opengl/error.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/opengl/error.c.o
.PHONY : src/opengl/error.c.o

src/opengl/error.i: src/opengl/error.c.i
.PHONY : src/opengl/error.i

# target to preprocess a source file
src/opengl/error.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/opengl/error.c.i
.PHONY : src/opengl/error.c.i

src/opengl/error.s: src/opengl/error.c.s
.PHONY : src/opengl/error.s

# target to generate assembly for a file
src/opengl/error.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/opengl/error.c.s
.PHONY : src/opengl/error.c.s

src/opengl/gl_window.o: src/opengl/gl_window.c.o
.PHONY : src/opengl/gl_window.o

# target to build an object file
src/opengl/gl_window.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/opengl/gl_window.c.o
.PHONY : src/opengl/gl_window.c.o

src/opengl/gl_window.i: src/opengl/gl_window.c.i
.PHONY : src/opengl/gl_window.i

# target to preprocess a source file
src/opengl/gl_window.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/opengl/gl_window.c.i
.PHONY : src/opengl/gl_window.c.i

src/opengl/gl_window.s: src/opengl/gl_window.c.s
.PHONY : src/opengl/gl_window.s

# target to generate assembly for a file
src/opengl/gl_window.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopadrome_BINARY.dir/build.make CMakeFiles/loopadrome_BINARY.dir/src/opengl/gl_window.c.s
.PHONY : src/opengl/gl_window.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... loopadrome_BINARY"
	@echo "... src/data/avl_tree.o"
	@echo "... src/data/avl_tree.i"
	@echo "... src/data/avl_tree.s"
	@echo "... src/data/list.o"
	@echo "... src/data/list.i"
	@echo "... src/data/list.s"
	@echo "... src/ecs/component.o"
	@echo "... src/ecs/component.i"
	@echo "... src/ecs/component.s"
	@echo "... src/ecs/entity.o"
	@echo "... src/ecs/entity.i"
	@echo "... src/ecs/entity.s"
	@echo "... src/ecs/system.o"
	@echo "... src/ecs/system.i"
	@echo "... src/ecs/system.s"
	@echo "... src/game/engine.o"
	@echo "... src/game/engine.i"
	@echo "... src/game/engine.s"
	@echo "... src/game/window/win_entity.o"
	@echo "... src/game/window/win_entity.i"
	@echo "... src/game/window/win_entity.s"
	@echo "... src/game/window/win_system.o"
	@echo "... src/game/window/win_system.i"
	@echo "... src/game/window/win_system.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/opengl/error.o"
	@echo "... src/opengl/error.i"
	@echo "... src/opengl/error.s"
	@echo "... src/opengl/gl_window.o"
	@echo "... src/opengl/gl_window.i"
	@echo "... src/opengl/gl_window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/dsampaio/Desenvolvimento/MelanciaSoftware/projects/loopadrome/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

